version: '3.8'


services:
  api:
    container_name: api
    build:
      context: ./api 
      args:
      - db_password=${DB_PASSWORD}
    ports:
      - '8000:8000'
    restart: on-failure
  client:
    build: ./client
    container_name: client
    ports: 
      - '3000:3000'
    depends_on:
      - api
    restart: on-failure
  db:
    build: ./db 
    container_name: db 
    ports: 
      - '3306:3306'
    depends_on:
      - api 
    