version: '3.8'



services:
  api:
    # build: ./api
    container_name: api_c
    image: index.docker.io/riggggo/website_2.0_api:latest
    ports:
      - '8000:8000'
    # volumes:
    #   - ./api:/app/api
    #   - ./app/api/node_modules
  
  client:
    # build: ./client
    container_name: client_container
    image: index.docker.io/riggggo/website_2.0_client:latest
    ports: 
      - '3000:3000'
    # volumes:
    #   - ./client:/app/client
    #   - ./app/client/node_modules 

    depends_on:
      - api
    stdin_open: true
    tty: true
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30