version: '3.8'



services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - '8000:8000'
    # volumes:
    #   - ./api:/app/api
    #   - ./app/api/node_modules
  client:
    build: ./client
    container_name: client_container
    ports: 
      - '3000:3000'
    # volumes:
    #   - ./client:/app/client
    #   - ./app/client/node_modules 
    stdin_open: true
    tty: true