version: '3.8'


services:
  api:
    container_name: api
    build:
      context: ./api 
      args:
      - db_password=${DB_PASSWORD}
    ports:
      - '8000:8000'
    stdin_open: true
    tty: true
    restart: on-failure
  client:
    build: ./client
    container_name: client
    ports: 
      - '3000:3000'
    depends_on:
      - api
    stdin_open: true
    tty: true