version: '3.8'



services:
  api:
    # build: ./api
    container_name: api
    image: index.docker.io/riggggo/website_2.0_api:latest
    ports:
      - '8000:8000'
    # volumes:
    #   - ./api:/app/api
    #   - ./app/api/node_modules
    stdin_open: true
    tty: true
    links:
      - mongo
  client:
    # build: ./client
    container_name: client_container
    image: index.docker.io/riggggo/website_2.0_client:latest
    ports: 
      - '3000:3000'
    # volumes:
    #   - ./client:/app/client
    #   - ./app/client/node_modules 

    depends_on:
      - api
      - website_1
    stdin_open: true
    tty: true
  website_1:
    container_name: website_1
    image: index.docker.io/riggggo/website_1.0:latest
    ports: 
      - '4000:4000'
    # volumes:
    #   - ./client:/app/client
    #   - ./app/client/node_modules 
    stdin_open: true
    tty: true
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30 --cleanup 