name: Create Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 # reuses already existing GitHub action
    
    - name: Build the Client Docker image
      run: docker build ./client --file ./client/Dockerfile --tag client
    - name: Build the API Docker image
      run: docker build ./api --file ./api/Dockerfile --tag api
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker push client
        run: docker tag client:latest ${{ secrets.DOCKERHUB_USERNAME }}/website_2.0_client 
        # && docker push ${{ secrets.DOCKERHUB_USERNAME }}/website_2.0_client:latest
      - name: Docker push api
        run: docker tag api:latest ${{ secrets.DOCKERHUB_USERNAME }}/website_2.0_api
        #  && docker push ${{ secrets.DOCKERHUB_USERNAME }}/website_2.0_api:latest
  


    
