name: Create and push Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 # reuses already existing GitHub action   
    - name: Build the Client Docker image
      run: docker build ./client --file ./client/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/website_2.0_client
    - name: Build the API Docker image
      run: docker build ./api --file ./api/Dockerfile --build-arg db_password=${{secrets.DB_PASSWORD}} --tag ${{ secrets.DOCKERHUB_USERNAME }}/website_2.0_api
    - name: Build the DB Docker image
      run: docker build ./db --file ./db/Dockerfile --build-arg db_root_password=${{secrets.DB_ROOT_PASSWORD}} --build-arg db_password=${{secrets.DB_PASSWORD}} --tag ${{ secrets.DOCKERHUB_USERNAME }}/website_2.0_db
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker push client
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/website_2.0_client:latest
    - name: Docker push api
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/website_2.0_api:latest
    - name: Docker push db
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/website_2.0_db:latest
  


    
